ext {
    //选择对应签名 "cainiao" "rockchip" "imx8" "freescale" "yt01"
    BUILD_SIGN="rockchip"
    BUILD_SIGN_PWD="android"
    BUILD_SIGN_PATH="../other/facefuture.jks"
    //android开发版本配置
    android = [
            compileSdkVersion         : 29,
            buildToolsVersion         : "29.0.2",
            minSdkVersion             : 19,
            targetSdkVersion          : 29,
            versionCode               : 27,
            versionName               : "1.4.5",
    ]
    //配置此项可对应生成不同的包名/应用图标 跳转不同界面
    APP_PKG_PREFIX='com.ichtj.'
    APP_CHOOSE='basetools'
    MY_ICON = [
            basetools               :'@drawable/app_img',
            socket                  :'@drawable/ic_socket',
            serialport              :'@drawable/ic_serialport',
            reboot                  :'@mipmap/reboot',
            netrecord               :'@drawable/ic_net_record',
            netmonitor              :'@mipmap/netmonitor',
            hidSubDev               :'@mipmap/ic_hid',
            hidMainDev              :'@mipmap/ic_hid',
            allApp                  :'@mipmap/ic_all_app',
            accessibility           :'@drawable/app_img',
            readimei                :'@mipmap/ic_all_app',
            testDemo                :'@mipmap/ic_all_app',
            cameraJni               :'@mipmap/ic_camera'
    ]
    //support配置
    support = [
            "constraint-layout"       : 'androidx.constraintlayout:constraintlayout:1.1.3',
            'appcompat'               : 'androidx.appcompat:appcompat:1.0.0',
            'recyclerview-v7'         : 'androidx.recyclerview:recyclerview:1.0.0',
            'annotations'             : 'androidx.annotation:annotation:1.0.0',
            'espresso'                : 'androidx.test.espresso:espresso-core:3.1.0',
            'runner'                  : 'androidx.test.ext:junit:1.1.1',
            'testCore'                : 'androidx.test:core:1.4.0',
            'multidex'                : 'androidx.multidex:multidex:2.0.0',
    ]
    //依赖第三方配置
    dependencies = [
            "AndroidAutoSize"         : "com.github.JessYanCoding:AndroidAutoSize:v1.2.1",
            "AndroidUSBCamera"        : "com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.2.10",
            "FastBle"                 : "com.github.Jasonchenlijian:FastBle:2.4.0",
            "BaseDrawable"            : "com.github.ichtj:BaseDrawable:1.0",
            "BluetoothHelper"         : "com.github.a-voyager:BluetoothHelper:f71d40a98b",
            "zxing"                   : "com.google.zxing:core:3.5.1",
            "converter-scalars"       : "com.squareup.retrofit2:converter-scalars:2.0.0",
            "rxjava"                  : "io.reactivex.rxjava3:rxjava:3.0.0-RC3",
            "rxandroid"               : "io.reactivex.rxjava2:rxandroid:2.1.1",
            //network
            "mqttv3"                  : "org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5",
            "mqttv-service"           : "org.eclipse.paho:org.eclipse.paho.android.service:1.1.1",
            //okhttp
            "okhttp12"                : "com.squareup.okhttp3:okhttp:3.12.1",
            "okhttp"                  : "com.squareup.okhttp3:okhttp:3.10.0",
            //rxjava
            "retrofit"                : "com.squareup.retrofit2:retrofit:2.6.2",
            "converter-gson"          : "com.squareup.retrofit2:converter-gson:2.6.2",
            "adapter-rxjava"          : "com.squareup.retrofit2:adapter-rxjava2:2.6.2",
            //eventbus
            "eventbus"                : "org.greenrobot:eventbus:3.1.1",
            //Arouter
            "arouter-compiler"        : "com.alibaba:arouter-compiler:1.5.2",
            "arouter-api"             : "com.alibaba:arouter-api:1.5.2",
            //json解析
            "gson"                    : "com.google.code.gson:gson:2.8.6",
            //物联网开发基础工具类
            "base_keepalive"          : "com.github.wave-chtj:BaseKeepAlive:1.0.1",
            "base_iotutils"           : "com.github.wave-chtj:BaseIotUtils:1.4.8",
            "base_framework"          : "com.github.ichtj:BaseFramework:1.5.2",
            "base_socket"             : "com.github.wave-chtj:BaseSocket:1.0.1",
            //rx系列与View生命周期同步
            "rxlifecycle"             : "com.trello.rxlifecycle2:rxlifecycle:2.2.2",
            "rxlifecycle-components"  : "com.trello.rxlifecycle2:rxlifecycle-components:2.2.2",
            //recycleView baseAdapter
            "base_adapter"            : "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.6",
            //ZIP压缩工具类
            "android_shell"           : "com.jrummyapps:android-shell:1.0.0",
            //ZIP压缩工具类
            "ziputils"                : "net.lingala.zip4j:zip4j:1.3.2",
            //Excel jxl表格工具
            "jxlutils"                : "net.sourceforge.jexcelapi:jxl:2.6.12",
            //内存泄漏工具
            "greendao"                : "org.greenrobot:greendao:3.3.0",
            //视频播放
            "videoplay"               : "cn.jzvd:jiaozivideoplayer:7.4.2",
    ]
}

