package com.wave_chtj.example.util;

public class FKey {
    public static final int              KEY_IMEI=0;//IMEI获取
    public static final int             KEY_ICCID=1;//ICCID获取
    public static final int          KEY_NET_TYPE=2;//网络类型
    public static final int       KEY_APK_VERSION=3;//Apk版本
    public static final int           KEY_IS_ROOT=4;//是否Root
    public static final int          KEY_LOCAL_IP=5;//本地IP
    public static final int        KEY_FW_VERSION=6;//固件版本
    public static final int               KEY_RAM=7;//系统RAM空间
    public static final int            KEY_SERIAL=8;//序列号
    public static final int          KEY_SD_SPACE=9;//SDcard空间
    public static final int         KEY_ETH_MODE=10;//以太网IP模式 静态 动态
    public static final int              KEY_DBM=11;//4G信号值
    public static final int      KEY_SERIAL_PORT=12;//串口收发
    public static final int           KEY_TIMERD=13;//定时器
    public static final int           KEY_SCREEN=14;//屏幕相关
    public static final int          KEY_FILE_RW=15;//文件读写
    public static final int          KEY_NETWORK=16;//网络监听
    public static final int    KEY_RESET_MONITOR=17;//网络重置监听
    public static final int         KEY_FILEDOWN=18;//文件下载
    public static final int          KEY_TCP_UDP=19;//TCP/UDP通讯
    public static final int      KEY_NOTIFY_SHOW=20;//状态栏通知
    public static final int     KEY_NOTIFY_CLOSE=21;//状态栏通知关闭
    public static final int  KEY_SYS_DIALOG_SHOW=22;//系统提示
    public static final int KEY_SYS_DIALOG_CLOSE=23;//系统提示关闭
    public static final int           KEY_DIALOG=24;//dialog
    public static final int            KEY_TOAST=25;//吐司
    public static final int         KEY_TOAST_BG=26;//带背景的吐司
    public static final int          KEY_ERR_ANR=27;//anr异常测试
    public static final int        KEY_ERR_OTHER=28;//其他异常测试
    public static final int          KEY_USB_HUB=29;//USB设备检测
    public static final int KEY_USB_HUB_UNREGIST=30;//取消USB设备检测
    public static final int        KEY_GREEN_DAO=31;//GreenDao数据库操作
    public static final int         KEY_JXL_OPEN=32;//jxl打开
    public static final int       KEY_JXL_EXPORT=33;//jxl导出
    public static final int         KEY_POI_OPEN=34;//poi打开
    public static final int       KEY_POI_EXPORT=35;//poi导出
    public static final int         KEY_APP_LIST=36;//App列表
    public static final int            KEY_VIDEO=37;//视频播放
    public static final int      KEY_URL_CONVERT=38;//Url转换
    public static final int           KEY_ASSETS=39;//本地资源获取
    public static final int            KEY_AUDIO=40;//音频播放
    public static final int    KEY_IP_SET_STATIC=41;//设置静态IP
    public static final int      KEY_IP_SET_DHCP=42;//设置动态IP
    public static final int       KEY_SCREENSHOT=43;//截屏
    public static final int        KEY_KEEPALIVE=44;//保活
    public static final int              KEY_OTA=45;//ota升级
    public static final int          KEY_INSTALL=46;//静默安装
    public static final int        KEY_BLUETOOTH=47;//蓝牙测试
    public static final int          VIDEO_CACHE=48;//视频录制
    public static final int            KEY_CRASH=49;//死机验证
    public static final int            KEY_NGINX=50;//nginx分布
    public static final int              KEY_HID=51;//HID开发
}