package com.wave_chtj.example.util;

public class FKey {
    public static final int          KEY_NET_TYPE=0;//网络类型
    public static final int       KEY_APK_VERSION=1;//Apk版本
    public static final int           KEY_IS_ROOT=2;//是否Root
    public static final int          KEY_LOCAL_IP=3;//本地IP
    public static final int        KEY_FW_VERSION=4;//固件版本
    public static final int               KEY_RAM=5;//系统RAM空间
    public static final int               KEY_ROM=6;//系统ROM空间
    public static final int          KEY_SD_SPACE=7;//SDcard空间
    public static final int          KEY_ETH_MODE=8;//以太网IP模式 静态 动态
    public static final int               KEY_DBM=9;//4G信号值
    public static final int      KEY_SERIAL_PORT=10;//串口收发
    public static final int           KEY_TIMERD=11;//定时器
    public static final int           KEY_SCREEN=12;//屏幕相关
    public static final int          KEY_FILE_RW=13;//文件读写
    public static final int          KEY_NETWORK=14;//网络监听
    public static final int    KEY_RESET_MONITOR=15;//网络重置监听
    public static final int         KEY_FILEDOWN=16;//文件下载
    public static final int          KEY_TCP_UDP=17;//TCP/UDP通讯
    public static final int      KEY_NOTIFY_SHOW=18;//状态栏通知
    public static final int     KEY_NOTIFY_CLOSE=19;//状态栏通知关闭
    public static final int  KEY_SYS_DIALOG_SHOW=20;//系统提示
    public static final int KEY_SYS_DIALOG_CLOSE=21;//系统提示关闭
    public static final int            KEY_TOAST=22;//吐司
    public static final int         KEY_TOAST_BG=23;//带背景的吐司
    public static final int          KEY_ERR_ANR=24;//anr异常测试
    public static final int        KEY_ERR_OTHER=25;//其他异常测试
    public static final int          KEY_USB_HUB=26;//USB设备检测
    public static final int KEY_USB_HUB_UNREGIST=27;//取消USB设备检测
    public static final int        KEY_GREEN_DAO=28;//GreenDao数据库操作
    public static final int         KEY_JXL_OPEN=29;//jxl打开
    public static final int       KEY_JXL_EXPORT=30;//jxl导出
    public static final int         KEY_POI_OPEN=31;//poi打开
    public static final int       KEY_POI_EXPORT=32;//poi导出
    public static final int         KEY_APP_LIST=33;//App列表
    public static final int            KEY_VIDEO=34;//视频播放
    public static final int      KEY_URL_CONVERT=35;//Url转换
    public static final int           KEY_ASSETS=36;//本地资源获取
    public static final int            KEY_AUDIO=37;//音频播放
    public static final int    KEY_IP_SET_STATIC=38;//设置静态IP
    public static final int      KEY_IP_SET_DHCP=39;//设置动态IP
    public static final int       KEY_SCREENSHOT=40;//截屏
    public static final int        KEY_KEEPALIVE=41;//保活
    public static final int              KEY_OTA=42;//ota升级
    public static final int          KEY_INSTALL=43;//静默安装
    public static final int            KEY_CRASH=44;//死机验证
    public static final int             KEY_MORE=45;//其他
}